"""empty message

Revision ID: 1911110c21eb
Revises: da35377fe679
Create Date: 2020-04-14 16:12:10.958765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1911110c21eb'
down_revision = 'da35377fe679'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('method_result_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['method_result_id'], ['method_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('method_results', sa.Column('user_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('method_results', 'user_score')
    op.drop_table('user_votes')
    # ### end Alembic commands ###
