"""empty message

Revision ID: 41fc11abae0d
Revises: 98d187a6d123
Create Date: 2020-04-11 16:49:31.529982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41fc11abae0d'
down_revision = '98d187a6d123'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('method_results', sa.Column('relevance_rating_title', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('method_results', 'relevance_rating_title')
    # ### end Alembic commands ###
