"""add search_results and method_results tables

Revision ID: 98d187a6d123
Revises: f95e673af427
Create Date: 2020-04-08 21:03:30.816427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98d187a6d123'
down_revision = 'f95e673af427'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('method_id', sa.Integer(), nullable=True),
    sa.Column('target_language_id', sa.Integer(), nullable=True),
    sa.Column('source_language_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['method_id'], ['methods.id'], ),
    sa.ForeignKeyConstraint(['source_language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['target_language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('method_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('method_id', sa.Integer(), nullable=True),
    sa.Column('search_result_id', sa.Integer(), nullable=True),
    sa.Column('relevance_rating', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['method_id'], ['methods.id'], ),
    sa.ForeignKeyConstraint(['search_result_id'], ['search_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('method_results')
    op.drop_table('search_results')
    # ### end Alembic commands ###
